// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateRecovery(ctx context.Context, arg CreateRecoveryParams) (CreateRecoveryRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// desconectar de todos os outros dispositivos
	DeleteAllUserSessionsExceptCurrent(ctx context.Context, arg DeleteAllUserSessionsExceptCurrentParams) error
	// usado no Logout
	DeleteSession(ctx context.Context, id string) error
	// busca apenas códigos que pertencem ao e-mail, não estão expirados, não foram usados e têm menos de 5 tentativas
	GetActiveRecoveryByCode(ctx context.Context, arg GetActiveRecoveryByCodeParams) (GetActiveRecoveryByCodeRow, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// registra um erro de digitação do código
	IncrementRecoveryAttempts(ctx context.Context, id int32) error
	// invalida o código imediatamente após o sucesso
	MarkRecoveryAsUsed(ctx context.Context, id int32) error
	// atualiza o last_verified_at e permite atualizar IP/Browser caso mudem sutilmente
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) error
}

var _ Querier = (*Queries)(nil)
