// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recoveries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecovery = `-- name: CreateRecovery :one
INSERT INTO recoveries (user_id, email, code, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, email, code, attempts, expired, expires_at, created_at, updated_at
`

type CreateRecoveryParams struct {
	UserID    string             `db:"user_id" json:"user_id"`
	Email     string             `db:"email" json:"email"`
	Code      string             `db:"code" json:"code"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRecovery(ctx context.Context, arg CreateRecoveryParams) (Recovery, error) {
	row := q.db.QueryRow(ctx, createRecovery,
		arg.UserID,
		arg.Email,
		arg.Code,
		arg.ExpiresAt,
	)
	var i Recovery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Code,
		&i.Attempts,
		&i.Expired,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRecoveryByCode = `-- name: GetActiveRecoveryByCode :one
SELECT id, user_id, email, code, attempts, expired, expires_at, created_at, updated_at
FROM recoveries
WHERE code = $1 
  AND email = $2 
  AND expired = FALSE 
  AND expires_at > NOW() 
  AND attempts < 5 
LIMIT 1
`

type GetActiveRecoveryByCodeParams struct {
	Code  string `db:"code" json:"code"`
	Email string `db:"email" json:"email"`
}

// busca apenas códigos que pertencem ao e-mail, não estão expirados, não foram usados e têm menos de 5 tentativas
func (q *Queries) GetActiveRecoveryByCode(ctx context.Context, arg GetActiveRecoveryByCodeParams) (Recovery, error) {
	row := q.db.QueryRow(ctx, getActiveRecoveryByCode, arg.Code, arg.Email)
	var i Recovery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Code,
		&i.Attempts,
		&i.Expired,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementRecoveryAttempts = `-- name: IncrementRecoveryAttempts :exec
UPDATE recoveries
SET attempts = attempts + 1
WHERE id = $1
`

// registra um erro de digitação do código
func (q *Queries) IncrementRecoveryAttempts(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementRecoveryAttempts, id)
	return err
}

const markRecoveryAsUsed = `-- name: MarkRecoveryAsUsed :exec
UPDATE recoveries
SET expired = TRUE
WHERE id = $1
`

// invalida o código imediatamente após o sucesso
func (q *Queries) MarkRecoveryAsUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markRecoveryAsUsed, id)
	return err
}
