// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, secret_hash, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, secret_hash, ip_address, user_agent, last_verified_at, created_at
`

type CreateSessionParams struct {
	ID         string      `db:"id" json:"id"`
	UserID     string      `db:"user_id" json:"user_id"`
	SecretHash []byte      `db:"secret_hash" json:"secret_hash"`
	IpAddress  *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent  pgtype.Text `db:"user_agent" json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.SecretHash,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllUserSessionsExceptCurrent = `-- name: DeleteAllUserSessionsExceptCurrent :exec
DELETE FROM sessions
WHERE user_id = $1 AND id <> $2
`

type DeleteAllUserSessionsExceptCurrentParams struct {
	UserID string `db:"user_id" json:"user_id"`
	ID     string `db:"id" json:"id"`
}

// desconectar de todos os outros dispositivos
func (q *Queries) DeleteAllUserSessionsExceptCurrent(ctx context.Context, arg DeleteAllUserSessionsExceptCurrentParams) error {
	_, err := q.db.Exec(ctx, deleteAllUserSessionsExceptCurrent, arg.UserID, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

// usado no Logout
func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, secret_hash, ip_address, user_agent, last_verified_at, created_at
FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions
SET last_verified_at = NOW(),
    ip_address = $2,
    user_agent = $3
WHERE id = $1
`

type UpdateSessionActivityParams struct {
	ID        string      `db:"id" json:"id"`
	IpAddress *netip.Addr `db:"ip_address" json:"ip_address"`
	UserAgent pgtype.Text `db:"user_agent" json:"user_agent"`
}

// atualiza o last_verified_at e permite atualizar IP/Browser caso mudem sutilmente
func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, arg.ID, arg.IpAddress, arg.UserAgent)
	return err
}
